### ISSUE TITLE
`visit()` video elements of type `mdxJsxFlowElement`?

### ISSUE THREAD

**Issue by karlhorky** [remcohaszing/rehype-mdx-import-media#2]
Hi @remcohaszing 👋 

I'm trying this out in our project, and I noticed that I am getting a different data structure than is maybe expected for `video` elements:

```
node {
  type: 'mdxJsxFlowElement',
  name: 'video',
  attributes: [
    {
      type: 'mdxJsxAttribute',
      name: 'src',
      value: './expo-android-virtual-device-start-expo-go.mp4',
      position: [Object]
    },
    {
      type: 'mdxJsxAttribute',
      name: 'controls',
      value: null,
      position: [Object]
    },
    {
      type: 'mdxJsxAttribute',
      name: 'style',
      value: [Object],
      position: [Object]
    }
  ],
  position: {
    start: { line: 7, column: 1, offset: 228 },
    end: { line: 16, column: 3, offset: 411 }
  },
  data: { _mdxExplicitJsx: true },
  children: []
}
```

This is for the following MDX:

```mdx
<video
 src="./expo-android-virtual-device-start-expo-go.mp4"
 controls
 style={{
   minWidth: 480,
   maxWidth: '70%',
   margin: '0 auto 1.45em',
   display: 'block',
 }}
/>
```

Would it be an idea to change the `'element'` on the line below to `['element', 'mdxJsxFlowElement']`?

https://github.com/remcohaszing/rehype-mdx-import-media/blob/61233bfd68e6395d21d727399adca026f8f44970/src/rehype-mdx-import-media.ts#L106

I'm thinking there will probably be other changes needed too for the attributes...  🤔

**Comment by karlhorky** [comment]
## Workaround

I applied this patch with [`patch-package`](https://www.npmjs.com/package/patch-package) in my `node_modules/rehype-mdx-import-media/dist/rehype-mdx-import-media.js` file:

```diff
```

**Comment by karlhorky** [comment]
Interestingly, the `<video>` tag cannot be overridden by MDXComponents - using the following configuration does not use my `Video` component (I could be misunderstanding how MDXComponents works with html tags though):

```ts
const components = {
  video: Video, // Not overriding `<video>` in MDX
} satisfies MDXComponents;

declare global {
  type MDXProvidedComponents = typeof components;
}

export function useMDXComponents(): MDXProvidedComponents {
  return components;
}
```

Maybe this is another symptom of the `'element'` vs `'mdxJsxFlowElement'` problem...?

**Comment by karlhorky** [comment]
> Interestingly, the `<video>` tag cannot be overridden by MDXComponents

Ah, looks like this is default behavior now with MDX:

- https://github.com/mdx-js/mdx/issues/821
- https://github.com/mdx-js/mdx/pull/2050
- https://github.com/mdx-js/mdx/pull/2052
- https://github.com/kentcdodds/mdx-bundler/issues/160

Surprising behavior, I would say, but I can also see why it would be surprising for people when the overriding did happen.

Edit: The [recommended workaround](https://github.com/kentcdodds/mdx-bundler/issues/160#issuecomment-1140526121) (originally from https://github.com/mdx-js/mdx/pull/2052#issuecomment-1140519087) doesn't appear to override HTML elements anymore in June 2024 unfortunately:

```js
{
  rehypePlugins: [
    () => (tree) => {
      visit(tree, "mdxJsxTextElement", (node) => {
        if (node.data) {
          delete node.data._mdxExplicitJsx;
        }
      });
    },
  ],
}
```

**Comment by karlhorky** [comment]
## Half-Workaround 1 (patch `rehype-mdx-import-media` to enable `<video>` support)

I applied this patch with [`patch-package`](https://www.npmjs.com/package/patch-package) in my `node_modules/rehype-mdx-import-media/dist/rehype-mdx-import-media.js` file.

```diff
diff --git a/node_modules/rehype-mdx-import-media/dist/rehype-mdx-import-media.js b/node_modules/rehype-mdx-import-media/dist/rehype-mdx-import-media.js
index b810804..5fae406 100644
--- a/node_modules/rehype-mdx-import-media/dist/rehype-mdx-import-media.js
+++ b/node_modules/rehype-mdx-import-media/dist/rehype-mdx-import-media.js
@@ -31,14 +31,18 @@ const rehypeMdxImportMedia = ({ attributes = defaultAttributes, elementAttribute
     return (ast) => {
         const imports = [];
         const imported = new Map();
-        visit(ast, 'element', (node, index, parent) => {
-            const attributeNames = elementMap.get(node.tagName);
+        // https://github.com/remcohaszing/rehype-mdx-import-media/issues/2#issuecomment-2198268795
+        visit(ast, ['element', 'mdxJsxFlowElement'], (node, index, parent) => {
+            const attributeNames = elementMap.get(node.tagName) || elementMap.get(node.name);
             if (!attributeNames) {
                 return;
             }
             let shouldReplace = false;
+            // https://github.com/remcohaszing/rehype-mdx-import-media/issues/2#issuecomment-2198268795
+            const attributesObject = node.attributes ? Object.fromEntries(node.attributes.map(({name, value}) => [name, value])) : {};
             // Don’t even bother continuing if there are no properties to replace.
-            for (const name in node.properties) {
+            // https://github.com/remcohaszing/rehype-mdx-import-media/issues/2#issuecomment-2198268795
+            for (const name in {...node.properties, ...attributesObject}) {
                 if (attributeNames.has(name.toLowerCase())) {
                     shouldReplace = true;
                     break;
@@ -107,7 +111,8 @@ const rehypeMdxImportMedia = ({ attributes = defaultAttributes, elementAttribute
                 shouldReplace = true;
                 return [{ type: 'Identifier', name }, propChunk];
             }
-            const replacements = propertiesToMdxJsxAttributes(node.properties, {
+            // https://github.com/remcohaszing/rehype-mdx-import-media/issues/2#issuecomment-2198268795
+            const replacements = propertiesToMdxJsxAttributes({...node.properties, ...attributesObject}, {
                 elementAttributeNameCase,
                 transform(name, value) {
                     if (!value) {
@@ -171,7 +176,8 @@ const rehypeMdxImportMedia = ({ attributes = defaultAttributes, elementAttribute
             if (shouldReplace) {
                 parent.children[index] = {
                     type: 'mdxJsxTextElement',
-                    name: node.tagName,
+                    // https://github.com/remcohaszing/rehype-mdx-import-media/issues/2#issuecomment-2198268795
+                    name: node.tagName || node.name,
                     attributes: replacements,
                     children: node.children,
                     data: node.data,
```

However, this crashes on `style` and `controls` attributes:

```mdx
<video
 src="./expo-android-virtual-device-start-expo-go.mp4"
 controls
 style={{
   minWidth: 480,
   maxWidth: '70%',
   margin: '0 auto 1.45em',
   display: 'block',
 }}
/>
```

with `this[node.value.type] is not a function`:

```
 ⨯ unhandledRejection: TypeError: this[node.value.type] is not a function
    at Object.Property (node_modules/@mdx-js/loader/node_modules/astring/dist/astring.mjs:829:28)
    at Object.ObjectExpression (node_modules/@mdx-js/loader/node_modules/astring/dist/astring.mjs:782:28)
    at formatSequence (node_modules/@mdx-js/loader/node_modules/astring/dist/astring.mjs:105:28)
    at Object.CallExpression (node_modules/@mdx-js/loader/node_modules/astring/dist/astring.mjs:989:5)
    at Object.ArrayExpression (node_modules/@mdx-js/loader/node_modules/astring/dist/astring.mjs:748:29)
    at Object.Property (node_modules/@mdx-js/loader/node_modules/astring/dist/astring.mjs:829:28)
    at Object.ObjectExpression (node_modules/@mdx-js/loader/node_modules/astring/dist/astring.mjs:782:28)
    at formatSequence (node_modules/@mdx-js/loader/node_modules/astring/dist/astring.mjs:105:28)
    at Object.CallExpression (node_modules/@mdx-js/loader/node_modules/astring/dist/astring.mjs:989:5)
    at Object.ArrayExpression (node_modules/@mdx-js/loader/node_modules/astring/dist/astring.mjs:748:29)
    at Object.Property (node_modules/@mdx-js/loader/node_modules/astring/dist/astring.mjs:829:28)
    at Object.ObjectExpression (node_modules/@mdx-js/loader/node_modules/astring/dist/astring.mjs:782:28)
    at formatSequence (node_modules/@mdx-js/loader/node_modules/astring/dist/astring.mjs:105:28)
    at Object.CallExpression (node_modules/@mdx-js/loader/node_modules/astring/dist/astring.mjs:989:5)
    at Object.ArrayExpression (node_modules/@mdx-js/loader/node_modules/astring/dist/astring.mjs:748:29)
    at Object.Property (node_modules/@mdx-js/loader/node_modules/astring/dist/astring.mjs:829:28)
    at Object.ObjectExpression (node_modules/@mdx-js/loader/node_modules/astring/dist/astring.mjs:782:28)
    at formatSequence (node_modules/@mdx-js/loader/node_modules/astring/dist/astring.mjs:105:28)
    at Object.CallExpression (node_modules/@mdx-js/loader/node_modules/astring/dist/astring.mjs:989:5)
    at Object.ReturnStatement (node_modules/@mdx-js/loader/node_modules/astring/dist/astring.mjs:413:31)
    at Object.BlockStatement (node_modules/@mdx-js/loader/node_modules/astring/dist/astring.mjs:294:29)
    at Object.FunctionDeclaration (node_modules/@mdx-js/loader/node_modules/astring/dist/astring.mjs:502:25)
    at Object.Program (node_modules/@mdx-js/loader/node_modules/astring/dist/astring.mjs:269:27)
    at generate (node_modules/@mdx-js/loader/node_modules/astring/dist/astring.mjs:1186:29)
    at toJs (node_modules/@mdx-js/loader/node_modules/estree-util-to-js/lib/index.js:133:17)
    at compiler (node_modules/@mdx-js/loader/node_modules/@mdx-js/mdx/lib/plugin/recma-stringify.js:34:9)
    at Function.stringify (node_modules/@mdx-js/loader/node_modules/unified/lib/index.js:1002:12)
    at node_modules/@mdx-js/loader/node_modules/unified/lib/index.js:749:36
    at realDone (node_modules/@mdx-js/loader/node_modules/unified/lib/index.js:921:11)
    at next (node_modules/@mdx-js/loader/node_modules/trough/lib/index.js:88:9)
    at done (node_modules/@mdx-js/loader/node_modules/trough/lib/index.js:194:7)
    at then (node_modules/@mdx-js/loader/node_modules/trough/lib/index.js:204:5)
    at wrapped (node_modules/@mdx-js/loader/node_modules/trough/lib/index.js:181:9)
    at next (node_modules/@mdx-js/loader/node_modules/trough/lib/index.js:86:23)
    at done (node_modules/@mdx-js/loader/node_modules/trough/lib/index.js:194:7)
    at then (node_modules/@mdx-js/loader/node_modules/trough/lib/index.js:204:5)
    at wrapped (node_modules/@mdx-js/loader/node_modules/trough/lib/index.js:181:9)
    at next (node_modules/@mdx-js/loader/node_modules/trough/lib/index.js:86:23)
    at done (node_modules/@mdx-js/loader/node_modules/trough/lib/index.js:194:7)
    at then (node_modules/@mdx-js/loader/node_modules/trough/lib/index.js:204:5)
    at wrapped (node_modules/@mdx-js/loader/node_modules/trough/lib/index.js:181:9)
    at next (node_modules/@mdx-js/loader/node_modules/trough/lib/index.js:86:23)
    at done (node_modules/@mdx-js/loader/node_modules/trough/lib/index.js:194:7)
    at then (node_modules/@mdx-js/loader/node_modules/trough/lib/index.js:204:5)
    at wrapped (node_modules/@mdx-js/loader/node_modules/trough/lib/index.js:181:9)
    at next (node_modules/@mdx-js/loader/node_modules/trough/lib/index.js:86:23)
    at done (node_modules/@mdx-js/loader/node_modules/trough/lib/index.js:194:7)
    at then (node_modules/@mdx-js/loader/node_modules/trough/lib/index.js:204:5)
```

**Comment by remcohaszing** [comment]
The behaviour is also described in the [_Usage_](https://github.com/remcohaszing/rehype-mdx-import-media#usage) section of the readme.

> This plugin takes HTML elements that refer to media content, and turns them into MDX expressions that use imports. This allows bundlers to resolve media you referenced from your code. Note that JSX elements are **not** HTML elements, so they are not processed. HTML elements can come from:
>
> - Markdown syntax in MDX files, such as images.
> - HTML in files parsed using the `md` [format](https://mdxjs.com/packages/mdx/#processoroptions) when using [`rehype-raw`](https://github.com/rehypejs/rehype-raw)
> - Custom remark / rehype plugins.

If you’re authoring MDX, you can write imports in your code.

```mdx
import virtualDeviceVideo from './expo-android-virtual-device-start-expo-go.mp4'

<video
  src={virtualDeviceVideo}
  controls
  style={{
    minWidth: 480,
    maxWidth: '70%',
    margin: '0 auto 1.45em',
    display: 'block',
  }}
/>
```

If this plugin *would* convert JSX, there would be too many edge cases.

**Comment by karlhorky** [comment]
## Workaround 2 (use remark plugin for `![]()` video syntax)

Markdown itself [does not have syntax for video](https://github.com/orgs/remarkjs/discussions/557#discussioncomment-120712), which seemingly would be required for using videos in `.mdx` files with `rehype-mdx-import-media`.

But copying and pasting [`@chailotl/remark-videos`](https://github.com/chailotl/remark-videos) into the `remarkPlugins` configuration enables [the `![]()` syntax for videos](https://stackoverflow.com/a/46296699/1268612)

`next.config.js`

```js
export default withMDX({
  options: {
    remarkPlugins: [
      // Copied from @chailotl/remark-videos
      // - https://github.com/chailotl/remark-videos
      // - https://www.npmjs.com/package/@chailotl/remark-videos
      () => (tree) => {
        visit(tree, 'image', (node) => {
          if (node.url.endsWith('.mp4')) {
            node.type = 'element';
            node.data = {
              hName: 'video',
              hProperties: {
                src: node.url,
              },
            };
          }
        });
      },
    ],
  },
})(config);
```

Then the following MDX will be processed by `rehype-mdx-import-media`:

```mdx
![](expo-android-virtual-device-close-app.mp4)
```

It will become something like:

```html
<video src="expo-android-virtual-device-close-app.mp4"></video>
```

**Comment by karlhorky** [comment]
> If you’re authoring MDX, you can write imports in your code.

I think that's what users would be trying to avoid with this plugin. Writing imports by hand is time intensive and error prone.

> The behaviour is also described in the [_Usage_](https://github.com/remcohaszing/rehype-mdx-import-media#usage) section of the readme.

Nice, thanks! I did see that afterwards, although it's only clear to me now, not when I first read it.

Would you be open to reopening this issue to become a "Add documentation" issue? There were quite a few hurdles and unexpected things to getting this working in an MDX integration with Next.js:

1. No Markdown syntax for videos
2. Using `<video>` in MDX doesn't get processed by `rehype-mdx-import-media`
3. imports don't work with Next.js + webpack v5 out of the box

I would suggest:

1. Adding a section for all elements that are not processed in MDX, and describing how to author them in MDX, with "blessed" recommendations:
   1. Recommending + documenting the `![]()` video syntax along with a copy + paste remark plugin as in Workaround 2 above, because it is a common syntax from the ecosystem
   2. Recommending + documenting the other alternatives like [`@chailotl/remark-videos`](https://www.npmjs.com/package/@chailotl/remark-videos) and [`rehype-video`](https://www.npmjs.com/package/rehype-video)
2. In the section for these elements described in the previous point, also include explicit language that mentions that `<video>`, `<img />` in MDX documents will not be processed
3. Adding a documentation recipe about how to configure Next.js + webpack v5 with `file-loader` so that imports to videos work (does not work out of the box)

**Comment by remcohaszing** [comment]
I’m open to improving the documentation, but I feel like your use case expands too much into Next.js specific configuration to document here.

> 1. No Markdown syntax for videos

You can use HTML tags in markdown files.

```html
<video
 src="./expo-android-virtual-device-start-expo-go.mp4"
 controls
></video>
```

You may need to use [`rehype-raw`](https://github.com/rehypejs/rehype-raw) for that. That would be noteworthy.

**Comment by karlhorky** [comment]
> I feel like your use case expands too much into Next.js specific configuration to document here

I think the problem is, where does this get documented then?

I did think through other locations to document it, and came to the conclusion that there is no better place to document 'integrating `rehype-mdx-import-media` with Next.js MDX' than here.

Other external locations (eg. MDX itself? webpack docs?) would also have the same objections that "'integrating `rehype-mdx-import-media` with Next.js MDX' does not belong in our docs", but then in the end, there is no proper place for the docs and it goes undocumented, with users having the downsides.

If you're open to it, reopening this issue (#2) and the other issue (#3) for docs additions in these areas would be cool.

**Comment by karlhorky** [comment]
I will, however, open an issue in MDX because [the current workaround to getting html elements overridden by `MDXComponents` (`delete node.data._mdxExplicitJsx`) no longer works](https://github.com/remcohaszing/rehype-mdx-import-media/issues/2#issuecomment-2198361734).

And maybe another one too about suggesting more documentation, recipes, onboarding for new users... 🤔 A lot of the solutions for things a bit beyond the MDX basics end up getting lost somewhere in some closed issue or PR.

**Comment by karlhorky** [comment]
Opened issues in MDX:

- workaround no longer working https://github.com/mdx-js/mdx/issues/2503
- recipes / examples ecosystem https://github.com/mdx-js/mdx/issues/2505
  - converted to a discussion https://github.com/orgs/mdx-js/discussions/2506

**Comment by karlhorky** [comment]
Added a trick to `mdx-tricks` to document [the Workaround 2 option](https://github.com/remcohaszing/rehype-mdx-import-media/issues/2#issuecomment-2198550703) to hijack Markdown image syntax for `.mp4` videos, along with the webpack `file-loader` config for the imports:

- https://github.com/karlhorky/mdx-tricks#relative-videos-without-imports

![Screenshot 2024-12-09 at 16 25 50](https://github.com/user-attachments/assets/2271b403-db8f-4885-8233-f9ceabcdba6e)

**Comment by talatkuyuk** [comment]
Hi @karlhorky,

**[`recma-mdx-import-media`](https://github.com/ipikuka/recma-mdx-import-media)** can process not only markdown image syntax **but also `<img />`, `<video />` and other media related jsx (built-in html) elements in MDX** in the same regard.
